apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-app
  labels:
    app: llm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm
  template:
    metadata:
      labels:
        app: llm
    spec:
      containers:
        - name: llm
          image: 499845095635.dkr.ecr.us-east-1.amazonaws.com/llm-app:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"

