name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: github.event.head_commit.message == 'k8s deploy'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: k8s

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.24.0"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name  eksdemo1 --region ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Run deploy_k8s.sh script
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          ECR_REPO_NAME: ${{ secrets.ECR_REPO_NAME }}
        run: |
          chmod +x ./deploy_k8s.sh
          ./deploy_k8s.sh

